#!/usr/bin/env node
/**
 * Vercel build sırasında html/config.js üretir.
 * Kaynak config.js git'e gitmez; ortam değişkenlerinden oluşturulur.
 */
const fs = require('fs');
const path = require('path');

const isProduction = process.env.VERCEL_ENV === 'production';
const appEnv = process.env.APP_ENV || (isProduction ? 'production' : 'development');

const vercelUrl = process.env.VERCEL_URL;
const apiBase =
  process.env.API_BASE_URL ||
  (vercelUrl ? `https://${vercelUrl}` : 'http://localhost:8000');

const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';

const allowFallback =
  appEnv !== 'production' && process.env.ALLOW_FALLBACK_ADMINS !== 'false';

const fallbackPassword = allowFallback
  ? process.env.FALLBACK_DEFAULT_PASSWORD || 'Crowe2022!'
  : '';

const fallbackAdmins = allowFallback
  ? {
      'admin.test@crowehsy.net': { fullName: 'Admin Test', role: 'admin' },
    }
  : {};

const content = `// Auto-generated by scripts/build-config.js — do not edit
const CONFIG_APP_ENV = '${appEnv}';

window.API_BASE_URL = window.API_BASE_URL || '${apiBase}';
window.SUPABASE_URL = window.SUPABASE_URL || '${supabaseUrl}';
window.SUPABASE_ANON_KEY = window.SUPABASE_ANON_KEY || '${supabaseAnonKey}';

const CONFIG_FALLBACK_DEFAULT_PASSWORD = ${JSON.stringify(fallbackPassword)};
const CONFIG_FALLBACK_ADMINS = ${JSON.stringify(fallbackAdmins, null, 4)};

window.APP_ENV = CONFIG_APP_ENV;
window.FALLBACK_DEFAULT_PASSWORD = CONFIG_FALLBACK_DEFAULT_PASSWORD;
window.FALLBACK_ADMINS = CONFIG_FALLBACK_ADMINS;

if (CONFIG_APP_ENV === 'production' && (CONFIG_FALLBACK_DEFAULT_PASSWORD || Object.keys(CONFIG_FALLBACK_ADMINS).length > 0)) {
  console.error('⚠️ Production modunda fallback admin aktif — güvenlik riski!');
}
`;

const outPath = path.join(__dirname, '..', 'html', 'config.js');
fs.writeFileSync(outPath, content, 'utf8');
console.log(`✓ config.js oluşturuldu (${appEnv}, API: ${apiBase})`);
